<?php

namespace App\Mappers;


class BaseMapper extends \Phalcon\Mvc\Model
{

    public static $hiddenAttributes = [];

    public function toArray($columns = null)
    {
        $arr = parent::toArray($columns);

        foreach (static::$hiddenAttributes as $attr) {
            unset($arr[$attr]);
        }

        return $arr;

    }

    public static function findFirst($parameters = null, $soft_deleted = false)
    {
        if (property_exists(static::class, 'deleted_at') && !$soft_deleted) {
            $parameters = self::softDeletedFilter($parameters);
        }

        return parent::findFirst($parameters);
    }

    public static function find($parameters = null, $soft_deleted = false)
    {
        if (property_exists(static::class, 'deleted_at') && !$soft_deleted) {
            $parameters = self::softDeletedFilter($parameters);
        }

        return parent::find($parameters);
    }

    public function getRelated($alias, $arguments = null, $soft_deleted = false)
    {
        $class = $this->getModelsManager()->getRelationByAlias(static::class, $alias)->getReferencedModel();
        if ($class && property_exists($class, 'deleted_at') && !$soft_deleted) {
            $arguments = self::softDeletedFilter($arguments);
        }

        return parent::getRelated($alias, $arguments);
    }

    public function save($data = null, $whiteList = null)
    {
        if (property_exists(static::class, 'updated_at')) {
            if ($data) {
                $data['updated_at'] = date('Y-m-d H:i:s');
            } else {
                $this->updated_at = date('Y-m-d H:i:s');
            }
        }

        parent::save($data, $whiteList); // TODO: Change the autogenerated stub
    }

    private static function softDeletedFilter($parameters = null)
    {
        if ($parameters) {
            if (isset($parameters['conditions'])) {
                $parameters['conditions'] .= ' and deleted_at is null';
            } else {
                $parameters['conditions'] = 'deleted_at is null';
            }
        } else {
            $parameters = [];
            $parameters['conditions'] = 'deleted_at is null';
        }

        return $parameters;
    }

}